export \
    WINESAPOS_IMAGE_TYPE=secure \
    WINESAPOS_ENCRYPT=true \
    WINESAPOS_APPARMOR=true \
    WINESAPOS_PASSWD_EXPIRE=true \
    WINESAPOS_SUDO_NO_PASSWORD=false \
    WINESAPOS_FIREWALL=true \
    WINESAPOS_CPU_MITIGATIONS=true \
    WINESAPOS_DISABLE_KWALLET=false \
    WINESAPOS_ENABLE_KLIPPER=false
