---
efiBootLoader: grub

kernel: /vmlinuz-linux

img: /initramfs-linux.img

fallback: /initramfs-linux-fallback.img

timeout: 10

grubInstall: grub-install

grubMkconfig: grub-mkconfig

grubCfg: /boot/grub/grub.cfg

efiBootloaderId: winesapOS
