---
# This module only supports 'crypttabOptions' and 'tmpOptions'. The mount options for each file
# system come from the 'mount' module, which stores them for this module to reuse.
crypttabOptions: luks

# winesapOS mounts /tmp as a RAM file system. Matches 'scripts/winesapos-install.sh'.
tmpOptions:
    default:
        tmpfs: true
        options: "rw,nosuid,nodev,inode64"
    ssd:
        tmpfs: true
        options: "rw,nosuid,nodev,inode64"
