---
efiSystemPartition: /boot/efi
efiSystemPartitionSize: 1024M
efiSystemPartitionName: WOS-EFI0

userSwapChoices:
    - none

drawNestedPartitions: false
alwaysShowPartitionLabels: true

defaultPartitionTableType: gpt

defaultFileSystemType: btrfs

availableFileSystemTypes:
    - btrfs

requiredPartitionTableType:
    - gpt

initialPartitioningChoice: alongside
initialSwapChoice: none

defaultPartitioningChoice: alongside
