---
# This runs inside of the target system, which is possible because the rootfs tarball has already
# been extracted by the 'shellprocess@unpack' module.
dontChroot: false

script:
    - command: "/bin/bash /usr/bin/winesapos-install-postcfg.sh"
      timeout: 900
