---
# Copy the running winesapOS installation into the target system. This runs outside of the target
# system because the target has no working shell until the files have been copied into it.
dontChroot: true

script:
    - command: "/bin/bash /usr/bin/winesapos-install-rootfs.sh ${ROOT}"
      timeout: 7200
