---
dontChroot: false

script:
    - command: "/bin/bash -c 'mkinitcpio -P'"
      timeout: 300
    - command: "/bin/bash -c 'e2label $(findmnt -n -o SOURCE /boot) winesapos-boot0 2>/dev/null || true'"
      timeout: 30
    - command: "/bin/bash -c 'btrfs filesystem label / winesapos-root0 2>/dev/null || true'"
      timeout: 30
