---
showSupportUrl: false
showKnownIssuesUrl: false
showReleaseNotesUrl: false

requirements:
    requiredStorage: 64
    requiredRam: 4.0
    internetCheckUrl: https://github.com
    check:
        - storage
        - ram
    required:
        - storage
