---
showSupportUrl: true
showKnownIssuesUrl: true
showReleaseNotesUrl: true

requirements:
    requiredStorage: 32
    requiredRam: 4.0
    internetCheckUrl: https://github.com
    check:
        - storage
        - ram
    required:
        - storage
