export \
    WINESAPOS_IMAGE_TYPE=minimal \
    WINESAPOS_ENABLE_PORTABLE_STORAGE=false \
    WINESAPOS_EXTRA_LINUX_FIRMWARE=false \
    WINESAPOS_INSTALL_GAMING_TOOLS=false \
    WINESAPOS_INSTALL_PRODUCTIVITY_TOOLS=false
