export \
    WINESAPOS_ENCRYPT=true \
    WINESAPOS_APPARMOR=true \
    WINESAPOS_PASSWD_EXPIRE=true \
    WINESAPOS_SUDO_NO_PASSWORD=false \
    WINESAPOS_FIREWALL=true \
    WINESAPOS_CPU_MITIGATIONS=true \
    WINESAPOS_DISABLE_KERNEL_UPDATES=false
